Create database Customer_behaviour
use [Customer_behaviour]
select * from [dbo].[customer_Behavior211]

--Q1. what is total revenue generated by male vs female customers?
select gender , sum(purchase_amount) as Total_Revenue  from [dbo].[customer_Behavior211]
group by gender

--q2. which customer used a discount but still spent more than the avearge purchase amount?
--avg=59
select customer_id ,avg(purchase_amount) [Avearge_purchase_amount]  from [dbo].[customer_Behavior211] 
where discount_applied ='Yes' 
group by customer_id
having avg(purchase_amount)> (select avg(purchase_amount) from  [dbo].[customer_Behavior211]
)

--Q3. which are the top 5 products with highest avearge review rating? avg=3.75005128243031
select distinct top 5 item_purchased , round(avg(review_rating),2) as RR from [dbo].[customer_Behavior211]
group by item_purchased
having avg(review_rating)>( select avg(review_rating) as rr from [dbo].[customer_Behavior211]
)
order by rr desc


--Q4. compare the average purchase amounts between standard and express shipping.
select * from [dbo].[customer_Behavior211]

select shipping_type,  round(Avg(purchase_amount),2)APA
from [dbo].[customer_Behavior211] where shipping_type='Express' or shipping_type= 'standard'  
group by shipping_type


select 
    max(case when shipping_type= 'Express' then Avgpa end) as Express_avg,
    max(case when shipping_type= 'standard' then Avgpa end) as standard_avg,
    max(case when shipping_type='Express' then Avgpa end)- max(case when shipping_type='Standard' then Avgpa end) as difference
    from (
         select shipping_type, avg(purchase_amount) as Avgpa from [dbo].[customer_Behavior211]
         group by shipping_type)
         t;


--Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non subscriber ?
select * from [dbo].[customer_Behavior211]

select subscription_status , 
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend ,
round(sum(purchase_amount),2) as total_revenue
from customer_Behavior211
group by subscription_status
order by total_revenue , avg_spend desc;

select 
    max(case when subscription_status='Yes' then SumA  end) as sum_of_subscription_Revenue ,
    max(case when subscription_status='No' then SumA  end ) as sum_of_Nonsubscription_Revenue, 
    max(case when  subscription_status ='Yes' then SumA  end) - max(case when subscription_status='No' then SumA  end) as difference_Revenue,
    max(case when subscription_status='Yes' then Agpa  end) as Avg_of_subscription_Revenue ,
    max(case when subscription_status='No' then Agpa  end ) as Avg_of_Nonsubscription_Revenue, 
    max(case when  subscription_status ='Yes' then Agpa  end) - max(case when subscription_status='No' then Agpa  end) as Avg_difference_Revenue
from (
         select subscription_status, sum(purchase_amount) as SumA, avg(purchase_amount) as Agpa from [dbo].[customer_Behavior211]
         group by subscription_status)
         t;



--Q6. which 5 products have highest percentage of purchase with discounts applied?
select top 5 item_purchased, 
    round(sum(case
        when discount_applied='Yes'
    then purchase_amount
    else 0 end) *100.0 / sum(purchase_amount),2) as percentage_discount
    from [dbo].[customer_Behavior211]
    group by item_purchased
    order by percentage_discount desc;

    select top 5 item_purchased,
    round(100* sum( case when discount_applied = 'Yes' Then 1 else 0 end)/count(*),2) as discount_rate
    from customer_Behavior211
    group by item_purchased
    order by discount_rate desc


--Q7. Segment customers into new , returning and loyal based on their total number of
--previous purchases , and show the count of each segment.
select * from customer_Behavior211

with customer_type as (
select customer_id , previous_purchases,
case 
    when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    Else 'Loyal'
    end as customer_segment
    from customer_Behavior211
    )

    
    select customer_segment , count(*) as number_of_customers
    from customer_type
    group by customer_segment
   


   

--Q8. What are the top 3 most purchased products within each category?
select category, item_purchased , purchased_count from (
select category , item_purchased , count(*) as purchased_count , 
ROW_NUMBER() OVER (partition by category order by count(*) desc) as rn 
from [dbo].[customer_Behavior211]
group by category , item_purchased) t
where rn<=3


--Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers 
from customer_Behavior211
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group ?
select age_group , sum(purchase_amount) as total_revenue 
from customer_Behavior211
group by age_group
order by total_revenue desc;



Update customer_Behavior211
set purchase_frequency_days = 120
where frequency_of_purchases ='Quarterly' 

Update customer_Behavior211
set purchase_frequency_days = 90
where frequency_of_purchases ='Every 3 Months'